name: "Fetch latest videos"
on:
    schedule:
        - cron: "0 5-17 * * *"
    workflow_dispatch:

jobs:
    fetch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install yt-dlp
              run: python3 -m pip install -U "yt-dlp[default]"
            - run: printf "${{ secrets.COOKIES }}" > cookies.txt
            - name: Fetch latest videos
              run: ./fetch.sh
            - name: Commit and push
              run: |
                git config user.name kambot
                git add -A
                git commit -am "[BOT] okun ciuram bababa"
                git push origin main
